server:
  port: 8182

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  max-attempts: 5
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: ${KAFKA_CONFIG_BOOTSTRAP_SERVERS:localhost:19092, localhost:29092, localhost:39092}
  schema-registry-url-key: schema.registry.url
  schema-registry-url: ${KAFKA_CONFIG_SCHEMA_REGISTRY_URL:http://localhost:8081}
  topic-name: ${KAFKA_CONFIG_TOPIC_NAME:twitter-topic}
  topic-names-to-create:
    - twitter-topic

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  consumer-group-id: twitter-topic-consumer-group
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: false
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150

elastic-config:
  index-name: ${ELASTIC_INDEX_NAME:twitter-index}
  connection-url: ${ELASTIC_CONNECTION_URL:http://localhost:9200}
  connection-timeout-ms: ${ELASTIC_CONNECTION_TIMEOUT_MS:5000}
  socket-timeout-ms: ${ELASTIC_SOCKET_TIMEOUT_MS:30000}
  use-repository: ${ELASTIC_USE_REPOSITORY:true}